//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reception03hosp45.DopService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DopService.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComUpdOrd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ComUpdOrd(string DatDocMdb, string DatDocTab, string DatDocKey, string DatDocIdn, string DatDocRek, string DatDocVal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComUpdOrd", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ComUpdOrdAsync(string DatDocMdb, string DatDocTab, string DatDocKey, string DatDocIdn, string DatDocRek, string DatDocVal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopInsKltOpl001", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DopInsKltOpl001(string BUXMDB, int BUXFRM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopInsKltOpl001", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DopInsKltOpl001Async(string BUXMDB, int BUXFRM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopInsKltOpl002", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DopInsKltOpl002(
                    string BUXMDB, 
                    int BUXFRM, 
                    string KLTOPLIDN, 
                    string KLTOPLDOC, 
                    string KLTOPLREF, 
                    string KLTOPLNUM, 
                    string OPLDATVIP, 
                    string OPLDATREG, 
                    string KLTOPLREG, 
                    string KLTOPLLPU, 
                    string KLTOPLUSL, 
                    string OPLDAT, 
                    string KLTOPLKRT, 
                    string KLTOPLKRTFAM, 
                    string KLTOPLFAM, 
                    string KLTOPLIMA, 
                    string KLTOPLFRM, 
                    string KLTOPLLIM, 
                    string KLTOPLVAL, 
                    string KLTOPLNAKSUM, 
                    string KLTOPLSSS, 
                    string KLTOPLLGT, 
                    string KLTOPLSUM, 
                    string KLTOPLRSX, 
                    string KLTOPLSUMDOL, 
                    string KLTOPLSUMEUR, 
                    string KLTOPLDNI, 
                    string KLTOPLNOZ, 
                    string KLTOPLDIG, 
                    string KLTOPLLCH, 
                    string KLTOPLMEM, 
                    string KLTOPLCNTTXT, 
                    string KLTOPLCNT, 
                    string OPLCNTBEG, 
                    string OPLCNTEND, 
                    string KLTOPLNAP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopInsKltOpl002", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DopInsKltOpl002Async(
                    string BUXMDB, 
                    int BUXFRM, 
                    string KLTOPLIDN, 
                    string KLTOPLDOC, 
                    string KLTOPLREF, 
                    string KLTOPLNUM, 
                    string OPLDATVIP, 
                    string OPLDATREG, 
                    string KLTOPLREG, 
                    string KLTOPLLPU, 
                    string KLTOPLUSL, 
                    string OPLDAT, 
                    string KLTOPLKRT, 
                    string KLTOPLKRTFAM, 
                    string KLTOPLFAM, 
                    string KLTOPLIMA, 
                    string KLTOPLFRM, 
                    string KLTOPLLIM, 
                    string KLTOPLVAL, 
                    string KLTOPLNAKSUM, 
                    string KLTOPLSSS, 
                    string KLTOPLLGT, 
                    string KLTOPLSUM, 
                    string KLTOPLRSX, 
                    string KLTOPLSUMDOL, 
                    string KLTOPLSUMEUR, 
                    string KLTOPLDNI, 
                    string KLTOPLNOZ, 
                    string KLTOPLDIG, 
                    string KLTOPLLCH, 
                    string KLTOPLMEM, 
                    string KLTOPLCNTTXT, 
                    string KLTOPLCNT, 
                    string OPLCNTBEG, 
                    string OPLCNTEND, 
                    string KLTOPLNAP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopInsKltOpl003", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DopInsKltOpl003(string BUXMDB, int BUXFRM, int LstBegIdn, int LstEndIdn, int KolIdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopInsKltOpl003", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DopInsKltOpl003Async(string BUXMDB, int BUXFRM, int LstBegIdn, int LstEndIdn, int KolIdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopRcpDocGrfTim", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DopRcpDocGrfTim(string BUXMDB, int BUXFRM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopRcpDocGrfTim", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DopRcpDocGrfTimAsync(string BUXMDB, int BUXFRM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuTabMaxIdn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DopStuTabMaxIdn(string BUXMDB, int BUXFRM, string BUXTAB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuTabMaxIdn", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DopStuTabMaxIdnAsync(string BUXMDB, int BUXFRM, string BUXTAB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuStt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DopStuStt(
                    string BUXMDB, 
                    int BUXFRM, 
                    string STTFRM, 
                    string STTIDN, 
                    string STTKOD, 
                    string STTGOD, 
                    string STTMES, 
                    string STTKEY, 
                    string STTKDR, 
                    string STTOC1, 
                    string STTNCH, 
                    string STTOPL, 
                    string STTOC2, 
                    string STTBEG, 
                    string STTEND, 
                    string STTPRX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuStt", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DopStuSttAsync(
                    string BUXMDB, 
                    int BUXFRM, 
                    string STTFRM, 
                    string STTIDN, 
                    string STTKOD, 
                    string STTGOD, 
                    string STTMES, 
                    string STTKEY, 
                    string STTKDR, 
                    string STTOC1, 
                    string STTNCH, 
                    string STTOPL, 
                    string STTOC2, 
                    string STTBEG, 
                    string STTEND, 
                    string STTPRX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuOpl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DopStuOpl(string BUXMDB, int BUXFRM, string OPLIDN, string OPLSTT, string OPLTAB, string OPLNUM, string OPLDAT, string OPLSUMKAZ, string OPLBNK, string OPLTIM, string OPLMEM, string OPLGOD, string OPLMES);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuOpl", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DopStuOplAsync(string BUXMDB, int BUXFRM, string OPLIDN, string OPLSTT, string OPLTAB, string OPLNUM, string OPLDAT, string OPLSUMKAZ, string OPLBNK, string OPLTIM, string OPLMEM, string OPLGOD, string OPLMES);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuKdr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DopStuKdr(string BUXMDB, int BUXFRM, string KOD, string KDRFAM, string KDRIMA, string KDROTC, string KDRRNN, string KDRFILCHT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuKdr", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DopStuKdrAsync(string BUXMDB, int BUXFRM, string KOD, string KDRFAM, string KDRIMA, string KDROTC, string KDRRNN, string KDRFILCHT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuSttUpd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DopStuSttUpd(string BUXMDB, int BUXFRM, string STTIDN, string STTKEY, string STTKDR, string STTOC1, string STTNCH, string STTOPL, string STTOC2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuSttUpd", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DopStuSttUpdAsync(string BUXMDB, int BUXFRM, string STTIDN, string STTKEY, string STTKDR, string STTOC1, string STTNCH, string STTOPL, string STTOC2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuFin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DopStuFin(string BUXMDB, int BUXFRM, string BUXTAB, int LstBegIdn, int LstEndIdn, int KolIdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopStuFin", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DopStuFinAsync(string BUXMDB, int BUXFRM, string BUXTAB, int LstBegIdn, int LstEndIdn, int KolIdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspRpn001", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DopHspRpn001(string BUXMDB, string BUXFRM, string BUXIIN, string BUXFIO, string BUXBRT, string BUXSEX, string BUXSTT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspRpn001", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DopHspRpn001Async(string BUXMDB, string BUXFRM, string BUXIIN, string BUXFIO, string BUXBRT, string BUXSEX, string BUXSTT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspRpn002", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DopHspRpn002(string BUXMDB, string KLTIDN, string KLTTEL, string KLTALR, string KLTADRPNK, string KLTADRSTR, string KLTADRDOM, string KLTADRAPR, string KLTADRETG, string KLTADRDMF, string KLTADRUGL, string KLTADRPOD, string KLTEML, string KLTRABNAM, string KLTRABDOL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspRpn002", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DopHspRpn002Async(string BUXMDB, string KLTIDN, string KLTTEL, string KLTALR, string KLTADRPNK, string KLTADRSTR, string KLTADRDOM, string KLTADRAPR, string KLTADRETG, string KLTADRDMF, string KLTADRUGL, string KLTADRPOD, string KLTEML, string KLTRABNAM, string KLTRABDOL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspAis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DopHspAis(string BUXFRM, string BUXIIN, string BUXIINBEG, string BUXIINEND, string BUXDATBEG, string BUXDATEND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspAis", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DopHspAisAsync(string BUXFRM, string BUXIIN, string BUXIINBEG, string BUXIINEND, string BUXDATBEG, string BUXDATEND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspAisKdu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DopHspAisKdu(string BUXFRM, string BUXIIN, string BUXIINBEG, string BUXIINEND, string BUXDATBEG, string BUXDATEND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspAisKdu", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DopHspAisKduAsync(string BUXFRM, string BUXIIN, string BUXIINBEG, string BUXIINEND, string BUXDATBEG, string BUXDATEND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspScr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DopHspScr(string BUXFRM, string BUXIIN, string BUXDATBEG, string BUXDATEND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspScr", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DopHspScrAsync(string BUXFRM, string BUXIIN, string BUXDATBEG, string BUXDATEND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspApp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DopHspApp(string BUXFRM, string BUXDAT, string BUXIDN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspApp", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DopHspAppAsync(string BUXFRM, string BUXDAT, string BUXIDN);
        
        // CODEGEN: Parameter 'DocBinaryArray' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveResearchDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reception03hosp45.DopService.SaveResearchDocumentResponse SaveResearchDocument(Reception03hosp45.DopService.SaveResearchDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveResearchDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<Reception03hosp45.DopService.SaveResearchDocumentResponse> SaveResearchDocumentAsync(Reception03hosp45.DopService.SaveResearchDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResearchDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetResearchDocument(string Login, string PassWord, string ClientIIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResearchDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetResearchDocumentAsync(string Login, string PassWord, string ClientIIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentIIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDocumentIIN(string Login, string PassWord, string ClientIIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentIIN", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDocumentIINAsync(string Login, string PassWord, string ClientIIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudIIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetStudIIN(string Login, string PassWord, string StudIIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudIIN", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStudIINAsync(string Login, string PassWord, string StudIIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudFIO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetStudFIO(string Login, string PassWord, string StudFam, string StudIma, string StudOtc, string StudBrt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudFIO", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStudFIOAsync(string Login, string PassWord, string StudFam, string StudIma, string StudOtc, string StudBrt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspRdb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DopHspRdb(string BUXFRM, string BUXIIN, string BUXCND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspRdb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DopHspRdbAsync(string BUXFRM, string BUXIIN, string BUXCND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspExpApp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DopHspExpApp(string BUXFRM, string BUXOPT, string BUXDATBEG, string BUXDATEND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopHspExpApp", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DopHspExpAppAsync(string BUXFRM, string BUXOPT, string BUXDATBEG, string BUXDATEND);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopServiceRPN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        Reception03hosp45.DopService.TaskOfString DopServiceRPN(string BUXFRM, string BUXIIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DopServiceRPN", ReplyAction="*")]
        System.Threading.Tasks.Task<Reception03hosp45.DopService.TaskOfString> DopServiceRPNAsync(string BUXFRM, string BUXIIN);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveResearchDocument", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveResearchDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string PassWord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ClientIIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string DateTimeOfResearch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string NameOfResearch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DocBinaryArray;
        
        public SaveResearchDocumentRequest() {
        }
        
        public SaveResearchDocumentRequest(string Login, string PassWord, string ClientIIN, string DateTimeOfResearch, string NameOfResearch, byte[] DocBinaryArray) {
            this.Login = Login;
            this.PassWord = PassWord;
            this.ClientIIN = ClientIIN;
            this.DateTimeOfResearch = DateTimeOfResearch;
            this.NameOfResearch = NameOfResearch;
            this.DocBinaryArray = DocBinaryArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveResearchDocumentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveResearchDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SaveResearchDocumentResult;
        
        public SaveResearchDocumentResponse() {
        }
        
        public SaveResearchDocumentResponse(bool SaveResearchDocumentResult) {
            this.SaveResearchDocumentResult = SaveResearchDocumentResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TaskOfString : Task {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaskOfString))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Task : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Reception03hosp45.DopService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Reception03hosp45.DopService.Service1Soap>, Reception03hosp45.DopService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ComUpdOrd(string DatDocMdb, string DatDocTab, string DatDocKey, string DatDocIdn, string DatDocRek, string DatDocVal) {
            return base.Channel.ComUpdOrd(DatDocMdb, DatDocTab, DatDocKey, DatDocIdn, DatDocRek, DatDocVal);
        }
        
        public System.Threading.Tasks.Task<bool> ComUpdOrdAsync(string DatDocMdb, string DatDocTab, string DatDocKey, string DatDocIdn, string DatDocRek, string DatDocVal) {
            return base.Channel.ComUpdOrdAsync(DatDocMdb, DatDocTab, DatDocKey, DatDocIdn, DatDocRek, DatDocVal);
        }
        
        public System.Data.DataSet DopInsKltOpl001(string BUXMDB, int BUXFRM) {
            return base.Channel.DopInsKltOpl001(BUXMDB, BUXFRM);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DopInsKltOpl001Async(string BUXMDB, int BUXFRM) {
            return base.Channel.DopInsKltOpl001Async(BUXMDB, BUXFRM);
        }
        
        public bool DopInsKltOpl002(
                    string BUXMDB, 
                    int BUXFRM, 
                    string KLTOPLIDN, 
                    string KLTOPLDOC, 
                    string KLTOPLREF, 
                    string KLTOPLNUM, 
                    string OPLDATVIP, 
                    string OPLDATREG, 
                    string KLTOPLREG, 
                    string KLTOPLLPU, 
                    string KLTOPLUSL, 
                    string OPLDAT, 
                    string KLTOPLKRT, 
                    string KLTOPLKRTFAM, 
                    string KLTOPLFAM, 
                    string KLTOPLIMA, 
                    string KLTOPLFRM, 
                    string KLTOPLLIM, 
                    string KLTOPLVAL, 
                    string KLTOPLNAKSUM, 
                    string KLTOPLSSS, 
                    string KLTOPLLGT, 
                    string KLTOPLSUM, 
                    string KLTOPLRSX, 
                    string KLTOPLSUMDOL, 
                    string KLTOPLSUMEUR, 
                    string KLTOPLDNI, 
                    string KLTOPLNOZ, 
                    string KLTOPLDIG, 
                    string KLTOPLLCH, 
                    string KLTOPLMEM, 
                    string KLTOPLCNTTXT, 
                    string KLTOPLCNT, 
                    string OPLCNTBEG, 
                    string OPLCNTEND, 
                    string KLTOPLNAP) {
            return base.Channel.DopInsKltOpl002(BUXMDB, BUXFRM, KLTOPLIDN, KLTOPLDOC, KLTOPLREF, KLTOPLNUM, OPLDATVIP, OPLDATREG, KLTOPLREG, KLTOPLLPU, KLTOPLUSL, OPLDAT, KLTOPLKRT, KLTOPLKRTFAM, KLTOPLFAM, KLTOPLIMA, KLTOPLFRM, KLTOPLLIM, KLTOPLVAL, KLTOPLNAKSUM, KLTOPLSSS, KLTOPLLGT, KLTOPLSUM, KLTOPLRSX, KLTOPLSUMDOL, KLTOPLSUMEUR, KLTOPLDNI, KLTOPLNOZ, KLTOPLDIG, KLTOPLLCH, KLTOPLMEM, KLTOPLCNTTXT, KLTOPLCNT, OPLCNTBEG, OPLCNTEND, KLTOPLNAP);
        }
        
        public System.Threading.Tasks.Task<bool> DopInsKltOpl002Async(
                    string BUXMDB, 
                    int BUXFRM, 
                    string KLTOPLIDN, 
                    string KLTOPLDOC, 
                    string KLTOPLREF, 
                    string KLTOPLNUM, 
                    string OPLDATVIP, 
                    string OPLDATREG, 
                    string KLTOPLREG, 
                    string KLTOPLLPU, 
                    string KLTOPLUSL, 
                    string OPLDAT, 
                    string KLTOPLKRT, 
                    string KLTOPLKRTFAM, 
                    string KLTOPLFAM, 
                    string KLTOPLIMA, 
                    string KLTOPLFRM, 
                    string KLTOPLLIM, 
                    string KLTOPLVAL, 
                    string KLTOPLNAKSUM, 
                    string KLTOPLSSS, 
                    string KLTOPLLGT, 
                    string KLTOPLSUM, 
                    string KLTOPLRSX, 
                    string KLTOPLSUMDOL, 
                    string KLTOPLSUMEUR, 
                    string KLTOPLDNI, 
                    string KLTOPLNOZ, 
                    string KLTOPLDIG, 
                    string KLTOPLLCH, 
                    string KLTOPLMEM, 
                    string KLTOPLCNTTXT, 
                    string KLTOPLCNT, 
                    string OPLCNTBEG, 
                    string OPLCNTEND, 
                    string KLTOPLNAP) {
            return base.Channel.DopInsKltOpl002Async(BUXMDB, BUXFRM, KLTOPLIDN, KLTOPLDOC, KLTOPLREF, KLTOPLNUM, OPLDATVIP, OPLDATREG, KLTOPLREG, KLTOPLLPU, KLTOPLUSL, OPLDAT, KLTOPLKRT, KLTOPLKRTFAM, KLTOPLFAM, KLTOPLIMA, KLTOPLFRM, KLTOPLLIM, KLTOPLVAL, KLTOPLNAKSUM, KLTOPLSSS, KLTOPLLGT, KLTOPLSUM, KLTOPLRSX, KLTOPLSUMDOL, KLTOPLSUMEUR, KLTOPLDNI, KLTOPLNOZ, KLTOPLDIG, KLTOPLLCH, KLTOPLMEM, KLTOPLCNTTXT, KLTOPLCNT, OPLCNTBEG, OPLCNTEND, KLTOPLNAP);
        }
        
        public bool DopInsKltOpl003(string BUXMDB, int BUXFRM, int LstBegIdn, int LstEndIdn, int KolIdn) {
            return base.Channel.DopInsKltOpl003(BUXMDB, BUXFRM, LstBegIdn, LstEndIdn, KolIdn);
        }
        
        public System.Threading.Tasks.Task<bool> DopInsKltOpl003Async(string BUXMDB, int BUXFRM, int LstBegIdn, int LstEndIdn, int KolIdn) {
            return base.Channel.DopInsKltOpl003Async(BUXMDB, BUXFRM, LstBegIdn, LstEndIdn, KolIdn);
        }
        
        public System.Data.DataSet DopRcpDocGrfTim(string BUXMDB, int BUXFRM) {
            return base.Channel.DopRcpDocGrfTim(BUXMDB, BUXFRM);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DopRcpDocGrfTimAsync(string BUXMDB, int BUXFRM) {
            return base.Channel.DopRcpDocGrfTimAsync(BUXMDB, BUXFRM);
        }
        
        public System.Data.DataSet DopStuTabMaxIdn(string BUXMDB, int BUXFRM, string BUXTAB) {
            return base.Channel.DopStuTabMaxIdn(BUXMDB, BUXFRM, BUXTAB);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DopStuTabMaxIdnAsync(string BUXMDB, int BUXFRM, string BUXTAB) {
            return base.Channel.DopStuTabMaxIdnAsync(BUXMDB, BUXFRM, BUXTAB);
        }
        
        public bool DopStuStt(
                    string BUXMDB, 
                    int BUXFRM, 
                    string STTFRM, 
                    string STTIDN, 
                    string STTKOD, 
                    string STTGOD, 
                    string STTMES, 
                    string STTKEY, 
                    string STTKDR, 
                    string STTOC1, 
                    string STTNCH, 
                    string STTOPL, 
                    string STTOC2, 
                    string STTBEG, 
                    string STTEND, 
                    string STTPRX) {
            return base.Channel.DopStuStt(BUXMDB, BUXFRM, STTFRM, STTIDN, STTKOD, STTGOD, STTMES, STTKEY, STTKDR, STTOC1, STTNCH, STTOPL, STTOC2, STTBEG, STTEND, STTPRX);
        }
        
        public System.Threading.Tasks.Task<bool> DopStuSttAsync(
                    string BUXMDB, 
                    int BUXFRM, 
                    string STTFRM, 
                    string STTIDN, 
                    string STTKOD, 
                    string STTGOD, 
                    string STTMES, 
                    string STTKEY, 
                    string STTKDR, 
                    string STTOC1, 
                    string STTNCH, 
                    string STTOPL, 
                    string STTOC2, 
                    string STTBEG, 
                    string STTEND, 
                    string STTPRX) {
            return base.Channel.DopStuSttAsync(BUXMDB, BUXFRM, STTFRM, STTIDN, STTKOD, STTGOD, STTMES, STTKEY, STTKDR, STTOC1, STTNCH, STTOPL, STTOC2, STTBEG, STTEND, STTPRX);
        }
        
        public bool DopStuOpl(string BUXMDB, int BUXFRM, string OPLIDN, string OPLSTT, string OPLTAB, string OPLNUM, string OPLDAT, string OPLSUMKAZ, string OPLBNK, string OPLTIM, string OPLMEM, string OPLGOD, string OPLMES) {
            return base.Channel.DopStuOpl(BUXMDB, BUXFRM, OPLIDN, OPLSTT, OPLTAB, OPLNUM, OPLDAT, OPLSUMKAZ, OPLBNK, OPLTIM, OPLMEM, OPLGOD, OPLMES);
        }
        
        public System.Threading.Tasks.Task<bool> DopStuOplAsync(string BUXMDB, int BUXFRM, string OPLIDN, string OPLSTT, string OPLTAB, string OPLNUM, string OPLDAT, string OPLSUMKAZ, string OPLBNK, string OPLTIM, string OPLMEM, string OPLGOD, string OPLMES) {
            return base.Channel.DopStuOplAsync(BUXMDB, BUXFRM, OPLIDN, OPLSTT, OPLTAB, OPLNUM, OPLDAT, OPLSUMKAZ, OPLBNK, OPLTIM, OPLMEM, OPLGOD, OPLMES);
        }
        
        public bool DopStuKdr(string BUXMDB, int BUXFRM, string KOD, string KDRFAM, string KDRIMA, string KDROTC, string KDRRNN, string KDRFILCHT) {
            return base.Channel.DopStuKdr(BUXMDB, BUXFRM, KOD, KDRFAM, KDRIMA, KDROTC, KDRRNN, KDRFILCHT);
        }
        
        public System.Threading.Tasks.Task<bool> DopStuKdrAsync(string BUXMDB, int BUXFRM, string KOD, string KDRFAM, string KDRIMA, string KDROTC, string KDRRNN, string KDRFILCHT) {
            return base.Channel.DopStuKdrAsync(BUXMDB, BUXFRM, KOD, KDRFAM, KDRIMA, KDROTC, KDRRNN, KDRFILCHT);
        }
        
        public bool DopStuSttUpd(string BUXMDB, int BUXFRM, string STTIDN, string STTKEY, string STTKDR, string STTOC1, string STTNCH, string STTOPL, string STTOC2) {
            return base.Channel.DopStuSttUpd(BUXMDB, BUXFRM, STTIDN, STTKEY, STTKDR, STTOC1, STTNCH, STTOPL, STTOC2);
        }
        
        public System.Threading.Tasks.Task<bool> DopStuSttUpdAsync(string BUXMDB, int BUXFRM, string STTIDN, string STTKEY, string STTKDR, string STTOC1, string STTNCH, string STTOPL, string STTOC2) {
            return base.Channel.DopStuSttUpdAsync(BUXMDB, BUXFRM, STTIDN, STTKEY, STTKDR, STTOC1, STTNCH, STTOPL, STTOC2);
        }
        
        public bool DopStuFin(string BUXMDB, int BUXFRM, string BUXTAB, int LstBegIdn, int LstEndIdn, int KolIdn) {
            return base.Channel.DopStuFin(BUXMDB, BUXFRM, BUXTAB, LstBegIdn, LstEndIdn, KolIdn);
        }
        
        public System.Threading.Tasks.Task<bool> DopStuFinAsync(string BUXMDB, int BUXFRM, string BUXTAB, int LstBegIdn, int LstEndIdn, int KolIdn) {
            return base.Channel.DopStuFinAsync(BUXMDB, BUXFRM, BUXTAB, LstBegIdn, LstEndIdn, KolIdn);
        }
        
        public System.Data.DataSet DopHspRpn001(string BUXMDB, string BUXFRM, string BUXIIN, string BUXFIO, string BUXBRT, string BUXSEX, string BUXSTT) {
            return base.Channel.DopHspRpn001(BUXMDB, BUXFRM, BUXIIN, BUXFIO, BUXBRT, BUXSEX, BUXSTT);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DopHspRpn001Async(string BUXMDB, string BUXFRM, string BUXIIN, string BUXFIO, string BUXBRT, string BUXSEX, string BUXSTT) {
            return base.Channel.DopHspRpn001Async(BUXMDB, BUXFRM, BUXIIN, BUXFIO, BUXBRT, BUXSEX, BUXSTT);
        }
        
        public bool DopHspRpn002(string BUXMDB, string KLTIDN, string KLTTEL, string KLTALR, string KLTADRPNK, string KLTADRSTR, string KLTADRDOM, string KLTADRAPR, string KLTADRETG, string KLTADRDMF, string KLTADRUGL, string KLTADRPOD, string KLTEML, string KLTRABNAM, string KLTRABDOL) {
            return base.Channel.DopHspRpn002(BUXMDB, KLTIDN, KLTTEL, KLTALR, KLTADRPNK, KLTADRSTR, KLTADRDOM, KLTADRAPR, KLTADRETG, KLTADRDMF, KLTADRUGL, KLTADRPOD, KLTEML, KLTRABNAM, KLTRABDOL);
        }
        
        public System.Threading.Tasks.Task<bool> DopHspRpn002Async(string BUXMDB, string KLTIDN, string KLTTEL, string KLTALR, string KLTADRPNK, string KLTADRSTR, string KLTADRDOM, string KLTADRAPR, string KLTADRETG, string KLTADRDMF, string KLTADRUGL, string KLTADRPOD, string KLTEML, string KLTRABNAM, string KLTRABDOL) {
            return base.Channel.DopHspRpn002Async(BUXMDB, KLTIDN, KLTTEL, KLTALR, KLTADRPNK, KLTADRSTR, KLTADRDOM, KLTADRAPR, KLTADRETG, KLTADRDMF, KLTADRUGL, KLTADRPOD, KLTEML, KLTRABNAM, KLTRABDOL);
        }
        
        public System.Data.DataSet DopHspAis(string BUXFRM, string BUXIIN, string BUXIINBEG, string BUXIINEND, string BUXDATBEG, string BUXDATEND) {
            return base.Channel.DopHspAis(BUXFRM, BUXIIN, BUXIINBEG, BUXIINEND, BUXDATBEG, BUXDATEND);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DopHspAisAsync(string BUXFRM, string BUXIIN, string BUXIINBEG, string BUXIINEND, string BUXDATBEG, string BUXDATEND) {
            return base.Channel.DopHspAisAsync(BUXFRM, BUXIIN, BUXIINBEG, BUXIINEND, BUXDATBEG, BUXDATEND);
        }
        
        public System.Data.DataSet DopHspAisKdu(string BUXFRM, string BUXIIN, string BUXIINBEG, string BUXIINEND, string BUXDATBEG, string BUXDATEND) {
            return base.Channel.DopHspAisKdu(BUXFRM, BUXIIN, BUXIINBEG, BUXIINEND, BUXDATBEG, BUXDATEND);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DopHspAisKduAsync(string BUXFRM, string BUXIIN, string BUXIINBEG, string BUXIINEND, string BUXDATBEG, string BUXDATEND) {
            return base.Channel.DopHspAisKduAsync(BUXFRM, BUXIIN, BUXIINBEG, BUXIINEND, BUXDATBEG, BUXDATEND);
        }
        
        public System.Data.DataSet DopHspScr(string BUXFRM, string BUXIIN, string BUXDATBEG, string BUXDATEND) {
            return base.Channel.DopHspScr(BUXFRM, BUXIIN, BUXDATBEG, BUXDATEND);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DopHspScrAsync(string BUXFRM, string BUXIIN, string BUXDATBEG, string BUXDATEND) {
            return base.Channel.DopHspScrAsync(BUXFRM, BUXIIN, BUXDATBEG, BUXDATEND);
        }
        
        public System.Data.DataSet DopHspApp(string BUXFRM, string BUXDAT, string BUXIDN) {
            return base.Channel.DopHspApp(BUXFRM, BUXDAT, BUXIDN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DopHspAppAsync(string BUXFRM, string BUXDAT, string BUXIDN) {
            return base.Channel.DopHspAppAsync(BUXFRM, BUXDAT, BUXIDN);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reception03hosp45.DopService.SaveResearchDocumentResponse Reception03hosp45.DopService.Service1Soap.SaveResearchDocument(Reception03hosp45.DopService.SaveResearchDocumentRequest request) {
            return base.Channel.SaveResearchDocument(request);
        }
        
        public bool SaveResearchDocument(string Login, string PassWord, string ClientIIN, string DateTimeOfResearch, string NameOfResearch, byte[] DocBinaryArray) {
            Reception03hosp45.DopService.SaveResearchDocumentRequest inValue = new Reception03hosp45.DopService.SaveResearchDocumentRequest();
            inValue.Login = Login;
            inValue.PassWord = PassWord;
            inValue.ClientIIN = ClientIIN;
            inValue.DateTimeOfResearch = DateTimeOfResearch;
            inValue.NameOfResearch = NameOfResearch;
            inValue.DocBinaryArray = DocBinaryArray;
            Reception03hosp45.DopService.SaveResearchDocumentResponse retVal = ((Reception03hosp45.DopService.Service1Soap)(this)).SaveResearchDocument(inValue);
            return retVal.SaveResearchDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reception03hosp45.DopService.SaveResearchDocumentResponse> Reception03hosp45.DopService.Service1Soap.SaveResearchDocumentAsync(Reception03hosp45.DopService.SaveResearchDocumentRequest request) {
            return base.Channel.SaveResearchDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reception03hosp45.DopService.SaveResearchDocumentResponse> SaveResearchDocumentAsync(string Login, string PassWord, string ClientIIN, string DateTimeOfResearch, string NameOfResearch, byte[] DocBinaryArray) {
            Reception03hosp45.DopService.SaveResearchDocumentRequest inValue = new Reception03hosp45.DopService.SaveResearchDocumentRequest();
            inValue.Login = Login;
            inValue.PassWord = PassWord;
            inValue.ClientIIN = ClientIIN;
            inValue.DateTimeOfResearch = DateTimeOfResearch;
            inValue.NameOfResearch = NameOfResearch;
            inValue.DocBinaryArray = DocBinaryArray;
            return ((Reception03hosp45.DopService.Service1Soap)(this)).SaveResearchDocumentAsync(inValue);
        }
        
        public System.Data.DataSet GetResearchDocument(string Login, string PassWord, string ClientIIN) {
            return base.Channel.GetResearchDocument(Login, PassWord, ClientIIN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetResearchDocumentAsync(string Login, string PassWord, string ClientIIN) {
            return base.Channel.GetResearchDocumentAsync(Login, PassWord, ClientIIN);
        }
        
        public System.Data.DataSet GetDocumentIIN(string Login, string PassWord, string ClientIIN) {
            return base.Channel.GetDocumentIIN(Login, PassWord, ClientIIN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDocumentIINAsync(string Login, string PassWord, string ClientIIN) {
            return base.Channel.GetDocumentIINAsync(Login, PassWord, ClientIIN);
        }
        
        public System.Data.DataSet GetStudIIN(string Login, string PassWord, string StudIIN) {
            return base.Channel.GetStudIIN(Login, PassWord, StudIIN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStudIINAsync(string Login, string PassWord, string StudIIN) {
            return base.Channel.GetStudIINAsync(Login, PassWord, StudIIN);
        }
        
        public System.Data.DataSet GetStudFIO(string Login, string PassWord, string StudFam, string StudIma, string StudOtc, string StudBrt) {
            return base.Channel.GetStudFIO(Login, PassWord, StudFam, StudIma, StudOtc, StudBrt);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStudFIOAsync(string Login, string PassWord, string StudFam, string StudIma, string StudOtc, string StudBrt) {
            return base.Channel.GetStudFIOAsync(Login, PassWord, StudFam, StudIma, StudOtc, StudBrt);
        }
        
        public System.Data.DataSet DopHspRdb(string BUXFRM, string BUXIIN, string BUXCND) {
            return base.Channel.DopHspRdb(BUXFRM, BUXIIN, BUXCND);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DopHspRdbAsync(string BUXFRM, string BUXIIN, string BUXCND) {
            return base.Channel.DopHspRdbAsync(BUXFRM, BUXIIN, BUXCND);
        }
        
        public System.Data.DataSet DopHspExpApp(string BUXFRM, string BUXOPT, string BUXDATBEG, string BUXDATEND) {
            return base.Channel.DopHspExpApp(BUXFRM, BUXOPT, BUXDATBEG, BUXDATEND);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DopHspExpAppAsync(string BUXFRM, string BUXOPT, string BUXDATBEG, string BUXDATEND) {
            return base.Channel.DopHspExpAppAsync(BUXFRM, BUXOPT, BUXDATBEG, BUXDATEND);
        }
        
        public Reception03hosp45.DopService.TaskOfString DopServiceRPN(string BUXFRM, string BUXIIN) {
            return base.Channel.DopServiceRPN(BUXFRM, BUXIIN);
        }
        
        public System.Threading.Tasks.Task<Reception03hosp45.DopService.TaskOfString> DopServiceRPNAsync(string BUXFRM, string BUXIIN) {
            return base.Channel.DopServiceRPNAsync(BUXFRM, BUXIIN);
        }
    }
}
